version: '3'

services:

  app:
    image: dev-circle
    ports:
      - 4000:4000
    links:
    - neo4j

  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
