version: '3'

services:

  app:
    image: dev-circle
    ports:
      - 4004:4004
    depends_on:
      - neo4j
      - redis
    links:
      - neo4j
      - redis
    environment:
      - NEO4J_URI=neo4j
      - REDIS_URI=redis

  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_AUTH=none
    volumes:
      - $PWD/neo4j/data:/data
      - $PWD/neo4j/plugins:/plugins

  redis:
    image: redis:latest
    ports:
      - 6379:6379
