version: '3'

services:

  app:
    image: dev-circle
    ports:
      - 4000:4000
    depends_on:
      - neo4j
      - redis
    links:
      - neo4j
      - redis
    environment:
      - NEO4J_URI=neo4j
      - REDIS_URI=redis

  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none

  redis:
    image: redis:latest
    ports:
      - 6379:6379
